Apply auto-formatting

diff --git a/sbin/issue-generator.in b/sbin/issue-generator.in
--- a/sbin/issue-generator.in
+++ b/sbin/issue-generator.in
@@ -13,113 +13,113 @@ PREFIX=""
 declare -A FILES
 
 find_files() {
-    for f in "${PREFIX}"/usr/lib/issue.d/* "${PREFIX}"/run/issue.d/* "${PREFIX}"/etc/issue.d/* ; do
-	test -f "$f" || continue
-	case "$f" in
-	    *.bak|*~|*.rpmsave|*.rpmnew)
-		echo "$f ignored"
-		continue
-		;;
-	    *.issue)
-		echo "$f ignored, printed by agetty"
-		continue
-		;;
-	esac
-	T=$(basename "$f")
-	FILES[${T}]="$f"
-    done
+	for f in "${PREFIX}"/usr/lib/issue.d/* "${PREFIX}"/run/issue.d/* "${PREFIX}"/etc/issue.d/*; do
+		test -f "$f" || continue
+		case "$f" in
+		*.bak | *~ | *.rpmsave | *.rpmnew)
+			echo "$f ignored"
+			continue
+			;;
+		*.issue)
+			echo "$f ignored, printed by agetty"
+			continue
+			;;
+		esac
+		T=$(basename "$f")
+		FILES[${T}]="$f"
+	done
 }
 
 generate_issue() {
-    for key in "${!FILES[@]}"; do
-	keys="${keys}\n${key}";
-    done
-    for key in $(echo -e ${keys} | sort -u); do
-	cat "${FILES[$key]}"
-    done
+	for key in "${!FILES[@]}"; do
+		keys="${keys}\n${key}"
+	done
+	for key in $(echo -e ${keys} | sort -u); do
+		cat "${FILES[$key]}"
+	done
 }
 
 usage() {
-    echo "Usage: issue-generator [--prefix <path>]"
-    echo "       issue-generator network add|remove interface|devpath"
-    echo "       issue-generator ssh add|remove"
-    exit $1
+	echo "Usage: issue-generator [--prefix <path>]"
+	echo "       issue-generator network add|remove interface|devpath"
+	echo "       issue-generator ssh add|remove"
+	exit $1
 }
 
 print_version() {
-    echo "issue-generator @VERSION@"
-    exit 0;
+	echo "issue-generator @VERSION@"
+	exit 0
 }
 
 while true; do
-    if [ $# -eq 0 ]; then
-        break
-    fi
+	if [ $# -eq 0 ]; then
+		break
+	fi
 
-    case "$1" in
+	case "$1" in
 	network)
-	    if [ $# -ne 3 ]; then
-		usage 1;
-	    fi
+		if [ $# -ne 3 ]; then
+			usage 1
+		fi
 
 		if [ -z "${NETWORK_INTERFACE_REGEX}" ]; then
 			NETWORK_INTERFACE_REGEX="^[be]"
 		fi
 
-	    # Support both ifname (eth0) as well as devpath (/devices/virtual/net/lo)
-	    if [[ "${3}" =~ ^/ ]]; then
-	        ifname="${3##*/}"
-	    else
-	        ifname="${3}"
-	    fi
+		# Support both ifname (eth0) as well as devpath (/devices/virtual/net/lo)
+		if [[ "${3}" =~ ^/ ]]; then
+			ifname="${3##*/}"
+		else
+			ifname="${3}"
+		fi
 
-	    [[ "${ifname}" =~ ${NETWORK_INTERFACE_REGEX} ]] || exit 0
+		[[ "${ifname}" =~ ${NETWORK_INTERFACE_REGEX} ]] || exit 0
 
-	    case "$2" in
+		case "$2" in
 		add)
-		    mkdir -p "${PREFIX}"/run/issue.d
-		    echo "${ifname}: \\4{$ifname} \\6{$ifname}" > "${PREFIX}/run/issue.d/70-$ifname.conf"
-		    ;;
-		del|delete|rm|remove)
-		    rm -f "${PREFIX}/run/issue.d/70-$ifname.conf"
-		    ;;
-	    esac
-	    shift 3;
-	    ;;
+			mkdir -p "${PREFIX}"/run/issue.d
+			echo "${ifname}: \\4{$ifname} \\6{$ifname}" >"${PREFIX}/run/issue.d/70-$ifname.conf"
+			;;
+		del | delete | rm | remove)
+			rm -f "${PREFIX}/run/issue.d/70-$ifname.conf"
+			;;
+		esac
+		shift 3
+		;;
 	ssh)
-	    if [ $# -ne 2 ]; then
-		usage 1;
-	    fi
+		if [ $# -ne 2 ]; then
+			usage 1
+		fi
 
-	    case "$2" in
+		case "$2" in
 		add)
-		    mkdir -p "${PREFIX}"/run/issue.d
-		    for KEY_FILE in $(find /etc/ssh -name 'ssh_host_*_key') ; do
-			ssh-keygen -l -f "${KEY_FILE}";
-		    done | awk '{print "SSH host key: " $2 " " $4}' > "${PREFIX}"/run/issue.d/60-ssh_host_keys.conf
-		    ;;
-		del|delete|rm|remove)
-		    rm -f "${PREFIX}"/run/issue.d/60-ssh_host_keys.conf
-		    ;;
-	    esac
-	    shift 2;
-	    ;;
+			mkdir -p "${PREFIX}"/run/issue.d
+			for KEY_FILE in $(find /etc/ssh -name 'ssh_host_*_key'); do
+				ssh-keygen -l -f "${KEY_FILE}"
+			done | awk '{print "SSH host key: " $2 " " $4}' >"${PREFIX}"/run/issue.d/60-ssh_host_keys.conf
+			;;
+		del | delete | rm | remove)
+			rm -f "${PREFIX}"/run/issue.d/60-ssh_host_keys.conf
+			;;
+		esac
+		shift 2
+		;;
 	--prefix)
-	    PREFIX=$2
-	    shift 2
-	    ;;
-	-h|--help)
-	    usage 0
-	    ;;
+		PREFIX=$2
+		shift 2
+		;;
+	-h | --help)
+		usage 0
+		;;
 	--version)
-	    print_version
-	    ;;
+		print_version
+		;;
 	*)
-	    if [ $# -ge 1 ]; then
-		usage 1;
-	    fi
-	    ;;
-    esac
+		if [ $# -ge 1 ]; then
+			usage 1
+		fi
+		;;
+	esac
 done
 
 find_files
@@ -127,22 +127,22 @@ find_files
 # really changed. And reload only in this case
 BACKUPFILE=$(mktemp -q "${PREFIX}"/run/issue.XXXXXXXXXX)
 if [ $? -ne 0 ]; then
-    echo "issue-generator: Can't create temp file..."
-    # Safe fallback: generate new file and reload
-    generate_issue > "${PREFIX}"/run/issue
-    RELOAD=1
-else
-    generate_issue > "${BACKUPFILE}"
-    cmp -s "${BACKUPFILE}" "${PREFIX}"/run/issue
-    if [ $? -ne 0 ]; then
-	chmod 644 "${BACKUPFILE}"
-	mv "${BACKUPFILE}" "${PREFIX}"/run/issue
+	echo "issue-generator: Can't create temp file..."
+	# Safe fallback: generate new file and reload
+	generate_issue >"${PREFIX}"/run/issue
 	RELOAD=1
-    else
-	rm -f "${BACKUPFILE}"
-	RELOAD=0
-    fi
+else
+	generate_issue >"${BACKUPFILE}"
+	cmp -s "${BACKUPFILE}" "${PREFIX}"/run/issue
+	if [ $? -ne 0 ]; then
+		chmod 644 "${BACKUPFILE}"
+		mv "${BACKUPFILE}" "${PREFIX}"/run/issue
+		RELOAD=1
+	else
+		rm -f "${BACKUPFILE}"
+		RELOAD=0
+	fi
 fi
 if [ ${RELOAD} -eq 1 ] && [ -e /run/agetty.reload ]; then
-    > /run/agetty.reload
+	>/run/agetty.reload
 fi
